# Generated by Django 2.2.7 on 2019-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='学号')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
            ],
            options={
                'verbose_name': '学生',
            },
        ),
    ]
